[package]
name = "algorithms"
version = "0.1.0"
authors = ["Nikolai Vazquez"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nvzqz/algorithms-rs"
description = """
Algorithms and data structures implemented in Rust for students, instructors, and curious people.
"""

[dependencies]
